name = "docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "wycbug.xyz"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "docker-proxy"
routes = [
  { pattern = "docker.wycbug.xyz", custom_domain = true },
  { pattern = "quay.wycbug.xyz", custom_domain = true },
  { pattern = "gcr.wycbug.xyz", custom_domain = true },
  { pattern = "k8s-gcr.wycbug.xyz", custom_domain = true },
  { pattern = "k8s.wycbug.xyz", custom_domain = true },
  { pattern = "ghcr.wycbug.xyz", custom_domain = true },
  { pattern = "cloudsmith.wycbug.xyz", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.wycbug.xyz", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
